#1 user want to hook their own http policy into the default http pipeline

  user can provide a HttpPolicy bean in the configuration,
  and we will ensure to pick
  up this bean and add it into the http pipeline

#2 user want to append a surfix to the user agent

logging.level

spring:
  cloud:
    azure:
      # common http configuration
      http:
        client:
          endpoint: xx
          applicationId: storage-blob
          headers:
            - name: test-header1
              values:
                - test1
                - test2
            - name: test-header2
              values:
                - test11
                - test22
        retry:
          xx: xx
        pipelinePolicies:
          xx: xx
      proxy:
        host: sdfsd
        port: 32
      credential:
        client-id: xx
        client-secert: xx
        tenant-id: xx
        certificate-path: C:\\storage\\ca\\202108\\certificate-auth.pem
      storage:
        blob:
          # inherit the properties
          proxy:
            xx: xx
          http:
            client:
              endpoint: xx
              applicationId: storage-blob
              headers:
                - name: test-header1
                  values:
                    - test1
                    - test2
                - name: test-header2
                  values:
                    - test11
                    - test22
            per-call-policies:
              - policyType:
                  policy: user_agent
                http-pipeline-position: per_call
                additional-parameters:
                  xx: xx
            per-retry-policies:
              - policyType:
                  policy: add_date
                http-pipeline-position: per_retry
                additional-parameters:
                  xx: xx
            retry:
              xx: xx
            perCallPolicies:
              - xx: xx
            perRetryPolicies:
              - xx: xx
          credential:
            client-id: xx
            client-secert: xx
            tenant-id: xx
            certificate-path: C:\\storage\\ca\\202108\\certificate-auth.pem
          cpk:
            key: xx
            keySha256: xx
            encryptionAlgorithm: AES256
          encryptionScope: XX
          containerName: XX
          blobName: xx
          snapshot: xx
          versionId: xx
          serviceVersion:
            version: 2020-06-12
        file:
          endpoint: https://teststorage.file.core.windows.net/

      keyvault:
        endpoint: ${KEY_VAULT_URI}
        credential:

          tenant-id: ${SERVICE_PRINCIPAL_TETANT}
          client-id: ${SERVICE_PRINCIPAL_ID}
          client-secret: ${SERVICE_PRINCIPAL_SECRET}
        secret:
          endpoint: https:ssdklfjsdlfjlsd
          proxy:
            host: aaa
            port: 2323
          credential:

            tenant-id: ${SERVICE_PRINCIPAL_TETANT}
            client-id: ${SERVICE_PRINCIPAL_ID}
            client-secret: ${SERVICE_PRINCIPAL_SECRET}
        certificates:
          endpoint: https://xcksdjlf.sdf.dsf


      cosmos:
        endpoint: https://demo-cosmos.documents.azure.com:443/
        database: demo-cosmos
        #key: xxx

        # inherit the credential
        credential:
          key-or-resource-token: xx
          client-id: xx
          client-secert: xx
        #    certificate-path: C:\\storage\\ca\\202108\\certificate-auth.pem
        proxy: